### ISSUE TITLE
[FEATURE REQUEST] CustomModelData Support for Item Model Customization

### ISSUE THREAD

**Issue by Stya-hr** [Luncaaa/AdvancedDisplays#3]
### Describe what you would like to see in a future version.

Hello there,

I'm really enjoying the functionality of your plugin in my server. I was wondering if it's possible to customize the models of displayed items directly through CustomModelData, as I've noticed you've implemented support for ItemsAdder. However, for certain reasons, I'm unable to use ItemsAdder to add and maintain new models directly.

Thank you for your help and for creating such a fantastic plugin! :)

**Comment by Luncaaa** [comment]
Hey @Kt3uNe , I'm glad you like my plugin :) I just implemented it in the latest dev build (download it [here](https://github.com/Luncaaa/AdvancedDisplays/releases/tag/dev))

You'll need to run the conversion command (remember to make a backup!) and it'll add a new setting to the item displays' settings: `customModelData`.

Let me know if it works as expected and thanks for your suggestion!

**Comment by Stya-hr** [comment]
![image](https://github.com/user-attachments/assets/5e4c0173-b364-4099-9714-20ab3df4ea68)
Thank you for the timely update, the `customModelData` configuration works perfectly. However, I seem to have encountered an **error** when trying to generate a `text_display`.

This occurred after I used the command `/ad create TEXT text2aug AUG`, and the **error log** is as follows:

```
[01:05:09 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ad' in plugin AdvancedDisplays v1.5.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:991) ~[paper-1.20.2.jar:git-Paper-292]
        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.2.jar:git-Paper-292]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:330) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:314) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2208) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$19(ServerGamePacketListenerImpl.java:2168) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-292]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-292]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-292]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-292]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-292]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-292]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-292]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-292]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.util.ImmutableCollections$ListN.get(ImmutableCollections.java:680) ~[?:?]
        at me.lucaaa.advanceddisplays.displays.AnimatedTextRunnable.start(AnimatedTextRunnable.java:48) ~[AdvancedDisplays-1.5.4.jar:?]
        at me.lucaaa.advanceddisplays.displays.AnimatedTextRunnable.start(AnimatedTextRunnable.java:40) ~[AdvancedDisplays-1.5.4.jar:?]
        at me.lucaaa.advanceddisplays.displays.ADTextDisplay.setRefreshTime(ADTextDisplay.java:348) ~[AdvancedDisplays-1.5.4.jar:?]
        at me.lucaaa.advanceddisplays.displays.ADTextDisplay.create(ADTextDisplay.java:87) ~[AdvancedDisplays-1.5.4.jar:?]
        at me.lucaaa.advanceddisplays.managers.DisplaysManager.createTextDisplay(DisplaysManager.java:177) ~[AdvancedDisplays-1.5.4.jar:?]
        at me.lucaaa.advanceddisplays.commands.subcommands.CreateSubCommand.run(CreateSubCommand.java:110) ~[AdvancedDisplays-1.5.4.jar:?]
        at me.lucaaa.advanceddisplays.commands.MainCommand.onCommand(MainCommand.java:75) ~[AdvancedDisplays-1.5.4.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more
```

After that, the corresponding configuration file and `text_display` were successfully generated, but it appears that the `texts` in configuration  is missing.

Should I open a new issue?

If further information is required, please let me know, although there might be a time difference.

**Comment by Luncaaa** [comment]
@Kt3uNe I should have fixed it in the new latest dev build. It'll take a couple of minutes for GitHub actions to upload it though. Try it and let me know if it fixed your issue. Thanks for reporting it!

**Comment by Stya-hr** [comment]
Great, it's working perfectly now, thank you for your help.
